### ISSUE TITLE
Not using specific icons

### ISSUE THREAD

**Issue by nwoltman** [braver/FileIcons#12]
Here's what I'm seeing with this package and the Adaptive theme in ST3 build 3200:

![sublime-icons](https://user-images.githubusercontent.com/5128013/54467420-61357480-475b-11e9-9afb-4e7714d2f8ec.png)

I would expect files like `postcss.config.js` and `webpack.config.js` to use their specific icons instead of the generic JavaScript icon. Is this package working as intended, or is this only not working for me?

I can see in this package's [`file_type_webpack.tmPreferences`](https://github.com/braver/FileIcons/blob/master/preferences/file_type_webpack.tmPreferences) file that it depends on the scope being `source.js.webpack`, but if this package doesn't do any of the complicated stuff that `A File Icon` does, then I'm not sure how the `webpack.config.js` file is supposed to have that scope.

**Comment by braver** [comment]
Well it will not have that scope because File Icons doesn't introduce an "alias" syntax for that kind of file. So for all Sublime Text knows, that's just a JavaScript file. If you really want the specific icon, you can create your alias syntaxes.

What probably works is dropping the aliases directory from A File Icon into your Packages dir (or perhaps just the few that you need):
https://github.com/SublimeText/AFileIcon/tree/master/aliases

(I should probably add a note about this in the README...)

**Comment by nwoltman** [comment]
Thanks for the explanation @braver! I saw the webpack icon in the icon sheet in the readme so I assumed File Icons would be able to display it without any extra steps. I guess I was hoping to get all the benefits of A File Icon but without the aliases 😅. Too bad Sublime doesn't make that easy.

**Comment by braver** [comment]
The aliases shouldn’t have any negative effects though, the scoping system makes it pretty much automatic and seemless. I don’t include them because it’s a bit messy and doesn’t add enough value. And if you do want the extra icons it’s an easy enough job to enable them. 🤷🏼‍♂️
