### ISSUE TITLE
Elixir icon doesn't match icon shown in the README

### ISSUE THREAD

**Issue by donileo** [braver/FileIcons#37]
The icon actually used is not as saturated (which I actually prefer). Not sure what other icons don't visually match.

**Comment by braver** [comment]
How doesn’t it match? Wrong color?

**Comment by donileo** [comment]
Here is what looks like in Sublime: 

<img width="28" alt="Screen Shot 2021-05-24 at 6 19 12 PM" src="https://user-images.githubusercontent.com/1881038/119414016-bfa3f900-bcbc-11eb-9714-c7842ad82e9d.png">

vs whats in the README photo:

<img width="52" alt="Screen Shot 2021-05-24 at 6 20 58 PM" src="https://user-images.githubusercontent.com/1881038/119414054-d4808c80-bcbc-11eb-9574-4769fbf8a852.png">

**Comment by braver** [comment]
Oh, right. At some point I adjusted the colors to match the default color schemes like Mariana more closely. I guess I didn’t update the image in the README (because that’s a hell of a lot of work). All purple icons are guaranteed to be the same purple. I think some icons may have gotten different colors over time, so that would also deviate from the README image.

You can of course install this package by cloning it into Packages. Then you can adjust the colors and run the build script to build a fresh set of icons all to your liking.

**Comment by braver** [comment]
I think 7962572 is what did it. I'm definitely not going to spend an hour trying to recreate that png though, but you're welcome  to open a PR 😉
