### ISSUE TITLE
Missing icons when no file extension

### ISSUE THREAD

**Issue by mrsdizzie** [braver/FileIcons#38]
Sorry if this is a duplicate of #15 but I didn't want to comment on a closed years old issue.

In that issue it says:

> So if you need ST to see a file type from the shebang, you need to update the syntax to do so. FileIcons only maps the syntax to an icon.

But I don't get a custom icon for any file without an extension even when all of those files have their syntax detected by Sublime via the ```first_line_match``` section in the syntax definition and have the same syntax as the files with extensions that are properly detected by FileIcons.

I tried in both Sublime Text 3 and the more recent Sublime Text 4 release but have the same issue in both. I'm probably just misunderstanding the comment above but wanted to check.

Thanks!

**Comment by braver** [comment]
Well, I guess I never looked into it fully. The main concept still stands though, all we can do here is map a syntax to an icon. That's the only thing the API allows as far as I know. I assumed that since syntaxes can recognise files on the first line basis, that would also be available to the sidebar. However, it doesn't. It seems reasonable that it doesn't because you'd have to open a file and read that first line to find the syntax and properly render the sidebar. Of course ST indexes everything, but for obvious reasons doesn't redraw the sidebar after the indexer is done.

So, the issue is with Sublime Text and can be reporter [there](https://github.com/sublimehq/sublime_text/issues), but there is nothing I can do. I don't think it likely this situation will change anytime soon, it being mostly cosmetic and having no clear path to resolution without performance and interaction downsides.
