### ISSUE TITLE
Not working with other themes

### ISSUE THREAD

**Issue by BarbzYHOOL** [braver/FileIcons#4]
It's like "a file icon" but for those who use default/adaptive UI theme, right?

I tried with soda solarized dark theme and it didn't display any icon

**Comment by braver** [comment]
Yeah, A File Icon does a bunch of on the fly processing and generates files so it can work with other themes. It’s messy, hacky and hard to maintain. So that’s why this exists, but it only works with the themes that ship with ST.

If you want to do some work it’s possible to make this work with another theme. Or theme authors can copy the source files and use it to build icons with colors matching the theme.

**Comment by BarbzYHOOL** [comment]
Well i'm new to sublimetext, new to python, so I rather not spend 1 week on this :P

However I use your solarized theme and your sidebartools :P

**Comment by braver** [comment]
Any particular reason you use soda instead of adaptive?

Perhaps I should make a little how-to. No python involved!

**Comment by BarbzYHOOL** [comment]
Well I infact changed to another theme than soda.

It's called Flat Solarized Dark.

You see the pattern? Your syntax theme is solarized, so I just tried other packages and Soda Solarized and Flat Solarized were the solarized version of the UI (aka theme). So everything is Solarized but both of these themes have small issues though

If it's really easy then why not a how to but I didn't see much issue with "a file icon" to be honest

**Comment by braver** [comment]
Well, Adaptive will match the Solarized colors too. 

Hey, if A File Icon works for you, why not. I don't like the hacks needed to make it work, whereas for a fixed set of themes a no-code solution is basically guaranteed to be bug free. But 🤷‍♂️
