### ISSUE TITLE
Could be possible to have a different color icon for an hpp file?

### ISSUE THREAD

**Issue by ellipticaldoor** [braver/FileIcons#40]
Because cpp and hpp both have the c++ syntax they get the same icon color.

![image](https://user-images.githubusercontent.com/3449006/121238115-a770d400-c88f-11eb-9c70-bf824a4e2e56.png)

Could be possible to assign a color by extension?

**Comment by braver** [comment]
It only works by syntax scope, so hopefully they’re differentiated in some way. I’d have to look 🤔

**Comment by ellipticaldoor** [comment]
Ah thank you, I think this is very useful. It also applies to opengl shaders

.frag and .vert they both have GLSL syntax, but is nice to have a different color in the icon to differentiate them like you can see on this screenshot in vscode

![image](https://user-images.githubusercontent.com/3449006/121240916-c0c74f80-c892-11eb-96f0-aa7ddd0f5bd5.png)

**Comment by braver** [comment]
Well, nope, the syntaxes are identical for those extensions. In theory, the main scope of say a `.hpp` could be `source.c++.h` or something instead of simply `source.c++`, and that would allow packages like this one to see that it's the-same-but-different from just c++. Right now though, and without changes to those core syntax packages, it's impossible without shenanigans (and this package is decidedly shenanigans-free 😉). A File Icon is sometimes known to introduce proxy-syntaxes to differentiate files that are otherwise the same syntax (e.g. Gruntfile, package.json, etc), they might take a different position towards the shenanigans you would need here.
