### ISSUE TITLE
Binary files

### ISSUE THREAD

**Issue by michaelblyons** [braver/FileIcons#9]
I notice you have icons for some Microsoft files (Word, etc.) as well as an "archive" icon for zip-like files. Is there a way to use those, or are they hanging around but inaccessible?

**Comment by braver** [comment]
Yes, it introduces dozens of “languages” for that purpose, or to for instance differentiate between a Grunfile and other JS files. It’s not terrible, but I personally don’t think it’s that important.

**Comment by braver** [comment]
I think the thing to do here is add fake, hidden, syntaxes for Word, Excel and Powerpoint. Since they can’t be edited anyway, there won’t be any other package trying the same thing. And IIRC you can create syntaxes that don’t show in the syntax selection list, or we might do something else to keep that clean.

And another syntax for archive files like zip, tar, etc. 

... might even use the zip syntax and icon for the MS Office files too because they’re technically zip files. 🧐
